name 'nginx'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@gmail.com'
license 'Apache-2.0'
description 'Installs and configures Nginx with comprehensive functionality'
version '1.0.0'
chef_version '>= 18.0'
source_url 'https://github.com/thomasvincent/chef-nginx-cookbook'
issues_url 'https://github.com/thomasvincent/chef-nginx-cookbook/issues'

supports 'ubuntu', '>= 20.04'
supports 'debian', '>= 11.0'
supports 'centos', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'amazon', '>= 2.0'
supports 'rocky', '>= 8.0'
supports 'alma', '>= 8.0'

depends 'build-essential', '>= 8.2'
depends 'yum-epel', '>= 4.1'
depends 'apt', '>= 8.0'
depends 'openssl', '>= 14.0'
depends 'selinux', '>= 6.0'

provides 'nginx::default'
provides 'nginx::install'
provides 'nginx::configure'
provides 'nginx::service'
provides 'nginx::sites'